### PR TITLE
Feature/react lazy

### PR DESCRIPTION
**Pull request by ciex**
Replaces deprecated react-loadable with React.lazy

- [x] Refactor module loading
- [x] Add error boundary / error handling during load
- [x] Add styled loading screen

Closes https://github.com/FixMyBerlin/fixmy.platform/issues/230

### CODE REVIEW

**Comment by geomC** [comment]
Can I review this once it's mergeable? I am interested how these things are implemented.

**Comment by ciex** [comment]
@geomC sure!

**Comment by geomC** [comment]
### Review tasks
* [ ] test error boundary
* [ ] inspect usage of `react.lazy` and `react.suspense`
* [ ] run e2e tests, manually test pages not convered
 *[ ] inspect Add styled loading screen

**Comment by geomC** [comment]
I tried throwing errors at a couple of places (e.g. by adding a `throw` clause [here](https://github.com/FixMyBerlin/fixmy.frontend/blob/develop/src/pages/Map/components/MapSwitch.js#L108) to provoke the `ErrorBoundary` rendering its content, without success.

@ciex Am I missing something here? Can you please point out where this kicks in?

**Comment by ciex** [comment]
@geomC the error boundary is activated for errors that occur during rendering. You can see it in action by adding `throw new Error('test');` in any render method.

**Pull request merged**
