### PR TITLE
Release 2022-02-xx

### PR DESCRIPTION
**Pull request by ohrie**
This includes several new features and fixes: #944, #936, #929, #941, #943, #943, #934, #955, #945.

Overall this is a new version of HBI which includes a new cadastre map layer.

In addition many dependencies were updated. Biggest change is the switch to Webpack 5 ( #912).

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Hejco** [comment]
- [ ] Textchange in overlay instead of upcoming...: [title]Happy-Bike-Index wird überarbeitet
[text]Wir arbeiten an der nächsten Version mit besseren Daten, wenn du bei der Datenerhebung in Open-Street-Map helfen möchtest schreib uns eine [mailto: info@fixmycity.de]Email [/mailto:]

- [ ] remove exit button in legend: using the legendbutton on the map for on/off should be enough. change off the appearance of the button would be nice (activated button: https://zpl.io/MdkqLo7)
- [ ] all HBI layer should be faded out from zoom 15.5 to Zoom 16.0: right now only HBI-track-overlay and HBI-intersection-overlay fade out (at higher zoom levels. --> see mapbox for layer names

- [ ] some strange behavior is accuring on some HBI-streets, other fadeout level and diagonal cutoffs. s, recording
- [ ] when filtering planings
Bildschirmfoto 2022-02-02 um 14 45 53
 pin and tracks should be hidden (now only pins)

**Comment by ohrie** [comment]
I've changed the logic for the visibility of the layers. But this is now hard coded in the code. The the mapbox style is changing, it does not automatically get's reflected in the code. Therefore we need to adapt the code when changes in Mapbox Studio get applied.
@Heiko How can we ensure that the code get's also adapted, when updating one of the HBI layers in Mapbox Studio ?

**Comment by tordans** [comment]
> How can we ensure that the code get's also adapted, when updating one of the HBI layers in Mapbox Studio ?

Every mayor change should be a new version of the Mapbox style which we have to change in the code at https://github.com/FixMyBerlin/fixmy.frontend/blob/b9cde7bc3ec6ce425e26c13332d436e51748befc/src/config/default/apps/map.ts#L3-L10. Could we add the list of layers that you refer to at this place as well so we have it in one place and know to check for updates?

**Comment by ohrie** [comment]
> . Could we add the list of layers that you refer to at this place as well so we have it in one place and know to check for updates?

If I understand you correct; My thought was more like, that the Studio editor should inform the developers when they've changed e.g. the opacity of a line of HBI. Since they need to be reflected in the code.

**Pull request merged**
