### PR TITLE
fix: cypress commands set window.initialState to state-slices instead…

### PR DESCRIPTION
**Pull request by s-pic**
Fixes https://github.com/FixMyBerlin/fixmy.platform/issues/349

see https://github.com/FixMyBerlin/fixmy.platform/issues/349#issuecomment-629837985

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Run e2e tests. The errors described in the issue dissapear (still tests are failing because of unrelated problems.

### CODE REVIEW

**Comment by ciex** [comment]
I'm a little confused why I apparently commited unrelated changes in this branch. They are already merged into `develop`, which is strange.

**Comment by s-pic** [comment]
Not sure either :D I'll branch off develop and cherry pick my commits and open another PR

**Comment by s-pic** [comment]
See https://github.com/FixMyBerlin/fixmy.frontend/pull/500

**Comment by ciex** [comment]
@s-pic sorry and thank you :)

**Pull request closed without merging**
