### PR TITLE
Kataster/e2e testing

### PR DESCRIPTION
**Pull request by geomC**
- [x] fix failing test in `scenes.test.js`
- [x] Move test files to their respective page
- [x] Review Documentation
- [x] Merge develop
- [x] Fix broken links to the app config after the changes https://github.com/FixMyBerlin/fixmy.frontend/pull/290 have been merged from /develop into  this branch

Closes https://github.com/FixMyBerlin/fixmy.platform/issues/125

### CODE REVIEW

**Comment by geomC** [comment]
@ciex One last thing before this is mergeable is to tackle a new problem introduced by https://github.com/FixMyBerlin/fixmy.frontend/pull/290:

The cypress code reads the config, e.g. [here](https://github.com/FixMyBerlin/fixmy.frontend/blob/kataster/e2e_testing/src/pages/KatasterKI/tests/e2e/landing.e2e.test.js#L2) ore [here](https://github.com/FixMyBerlin/fixmy.frontend/blob/kataster/e2e_testing/cypress/support/commands.js#L6). 

After I have merged the latest changes from develop, the tests fail because they are still pointing to the old JavaScript config file.

Since you did the config refactoring and since you will be doing the review – can you please look into this?

**Comment by ciex** [comment]
The imports using lots of `/../` were pointing at wrong directories. You can often avoid this kind of error by using alias-based imports when they result in a shorter path (i.e. `~/config` instead of `.././.).

Cypress also seemed to require access to the webpack configuration in order to handle Typescript files correctly. I added this [here](https://github.com/FixMyBerlin/fixmy.frontend/pull/291/commits/e6b93e0a003eef20f50906c5fcf64b111d319ce5).

Weirdly, I *sometimes* get an error related to a missing file in the project build that cypress is making internally. The file is `cypress/support/index.js`, which doesn't seem to be built *sometimes*.

I have gotten the most consistent results when running `cypress open` and then manually triggering test runs, while `cypress run --headed` seemed to fail less often and `cypress run` most often. This seems to indicate a timing problem - maybe related to Typescript compilation?

**Comment by ciex** [comment]
Also there seem to be missing `[data-cy=...]` declarations. I fixed one for the landing-spec but some of the tests just seem to fail because cypress is expecting these on the elements and not finding them.

**Comment by ciex** [comment]
This is the status quo now:

```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  pages/KatasterKI/tests/e2e/landing.      00:02        1        1        -        -        - │
  │    e2e.test.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  pages/KatasterKI/tests/e2e/profiles      01:00       19        4       12        -        3 │
  │    .e2e.test.js                                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  pages/KatasterKI/tests/e2e/scenes.e      00:19       28       28        -        -        - │
  │    2e.test.js                                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  pages/Map/tests/planungen.e2e.test.      00:16        4        4        -        -        - │
  │    js                                                                                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 4 failed (25%)                      01:38       52       37       12        -        3
```

**Comment by geomC** [comment]
> The imports using lots of /../ were pointing at wrong directories. You can often avoid this kind of error by using alias-based imports when they result in a shorter path (i.e. ~/config instead of ../../../../config.

After I merged /developement, I fixed those paths locally. I did not commit it since the config - now being TS code - was not handled correctly.

>Cypress also seemed to require access to the webpack configuration in order to handle Typescript files correctly. I added this here.

Thanks! Thought I did that already..

>Also there seem to be missing [data-cy=...] declarations. I fixed one for the landing-spec but some of the tests just seem to fail because cypress is expecting these on the elements and not finding them.

Eventually some unpushed work. Sorry!

**Comment by ciex** [comment]
ok, good!

> I have gotten the most consistent results when running `cypress open` and then manually triggering test runs, while `cypress run --headed` seemed to fail less often and `cypress run` most often. This seems to indicate a timing problem - maybe related to Typescript compilation?

@geomC can you confirm this?

**Comment by geomC** [comment]
Hey @ciex, sorry for the delay.

I am looking into the errors you stated.
Starting with this:

> Weirdly, I sometimes get an error related to a missing file in the project build that cypress is making internally. The file is cypress/support/index.js, which doesn't seem to be built sometimes.

AFAIK this file is static and dies not get compiled at some point. https://github.com/FixMyBerlin/fixmy.frontend/pull/291/files#diff-2b07e229b86aa9d270302ce5fcdf29a1

**Comment by geomC** [comment]
I looked into this further

* https://github.com/FixMyBerlin/fixmy.frontend/pull/291/commits/e42714697d18affeee6562fc958f2be31a86f963 did indeed delete a data-cy declaration which has been problematic, but yet fixed in https://github.com/FixMyBerlin/fixmy.frontend/pull/291/commits/ad414de2bb09a9b87dd17b70a71c757b003cfc7c
* The `cypress.get()` queries in `profiles.e2e.test.js` apperently fail because the loadeded survey items are now differing from what has been expected up to some point. E.g. the first failing test looks for `[data-cy=kat-singlechoice-btn]`, but what gets loaded is a suryey item containing a `[data-cy=kat-multichoice-proceed-btn]`.

I am not sure what commit introduced the shuffling, I assume its https://github.com/FixMyBerlin/fixmy.frontend/pull/291/commits/e42714697d18affeee6562fc958f2be31a86f963.

**Pull request merged**
